# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'Locksmith'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleAnalytics'
  pod 'ReachabilitySwift'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'

end
